INSERT INTO brand (name)
VALUES
    ('Maybelline New York'),
    ('Loreal Paris'),
    ('Artdeco'),
    ('Lamel Professional'),
    ('NYX'),
    ('Estee Lauder'),
    ('Chanel'),
    ('Versace'),
    ('Dior');

INSERT INTO person (role, login, password,firstname,lastname)
VALUES
    ('ADMIN', 'admin-yuliana', 'yuliana-admin', 'Yuliana', 'Bilack'),
    ('ADMIN', 'admin-emiliia', 'emilia-admin', 'Emilia', 'Dragomirecha'),
    ('ADMIN', 'admin-mykola', 'mykola-admin', 'Mykola', 'Shumeyko');

INSERT INTO product (name, description, brandId, price, category, color, volume, photoPath)
VALUES
    ('Lash Sensational', 'Drive crazy and delight with just one look.
 Take care of your lashes with Maybelline New York Mascara.', 1, 8.29, 'MAKEUP',
     '#000000', '9.5 ml', 'assets/images/makeup/makeup1.jpg'),
    ('Color Riche Ultra Matte', 'Ultra-matte lipstick', 2, 9.61, 'MAKEUP', '#9f5057',
     '4.5 ml', 'assets/images/makeup/makeup2.jpg'),
    ('Concealer Wand', 'Great liquid Concealer Wand concealer, thanks to which you can easily hide any imperfections and darkening in the eye area.', 5, 9.44, 'MAKEUP',
     '#f6e6d3', '3 g', 'assets/images/makeup/makeup3.jpg'),
    ('Eyeshadow Base', 'Eyeshadow Base with a delicate, creamy consistency.', 3, 6.26, 'MAKEUP',
     '#d8b590', '5 ml', 'assets/images/makeup/makeup4.jpg'),
    ('Eyeshadow Pearl', 'Deep shades of eyeshadow paired with a light pearlescent shade.', 3, 3.11, 'MAKEUP',
     '#dfb5c5', '0.8 g', 'assets/images/makeup/makeup5.jpg'),
    ('Alliance Perfect', 'Light facial foundation with hyaluronic acid. The innovative formula of the tonal cream will make your makeup perfect and elegant, giving your face purity, mystery and a gentle glow.', 2, 8.12, 'MAKEUP',
     '#fbd3b3', '30 ml', 'assets/images/makeup/makeup6.jpg'),
    ('True Match', 'True Match high-quality face concealer will help quickly and effectively hide redness, small pimples, signs of fatigue and dark circles under the eyes, giving the skin a healthy glow.', 2, 6.22, 'MAKEUP',
     '#efcfb8', '6.8 ml', 'assets/images/makeup/makeup7.jpg'),
    ('Futurist Aqua Brilliance Makeup SPF 20', 'Illuminate the beauty of your skin. Infused with our exclusive Sustainable Moisture Complex™ and Revival Plant Extract, this makeup helps create a ' ||
                                               'surge of fresh radiance. Skin looks brighter instantly. Hydrates with a skin-caring blend of moisturizers and conditioners. ' ||
                                               'Helps improve moisture and keep skin looking brighter, dewy and plump. Fine drylines and imperfections seem to disappear. ' ||
                                               'All you see is flawless brilliance. For all skintypes.', 6, 13.21, 'MAKEUP',
     '#ceab89', '10 ml', 'assets/images/makeup/makeup8.jpg'),
    ('Fit Me Matte Poreless Powder', 'Fit Me® Matte + Poreless Powder face makeup. Mattifies and leaves a poreless-looking finish with long-lasting shine control. Ideal for normal to oily skin, this long-lasting powder leaves a natural, poreless-looking finish with long-lasting shine control.', 1, 8.49, 'MAKEUP',
     '#f6c17c', '9 g', 'assets/images/makeup/makeup9.jpg'),
    ('Lip Cream Plump & Care', 'Give your lips a combination of loving care. Lip Cream Plump & Care instantly transforms dry and chapped lips into seductive, full of sensuality and delicate touch. ', 4, 5.49, 'MAKEUP',
     '#ffc6df', '6 ml', 'assets/images/makeup/makeup10.jpg'),
    ('HD Highlighting Glow & Sparkle Powder', 'It has a light texture that creates a weightless, shimmering layer on the skin. Thanks to small light-reflecting particles, the face acquires a gentle, soft, natural shine. The decorative tool will help correct facial features - highlight the cheekbones, visually raise the eyebrows, open the eyes and give the lips a lush volume. It minimizes the appearance of pigmentation and hides age changes.', 4, 5.68, 'MAKEUP',
     '#d6b9aa', '12 g', 'assets/images/makeup/makeup11.jpg'),
    ('Lipliner', ' With the help of the lipliner, you can quickly emphasize the contour and visually correct the shape of the lips. And all this against the background of practical advantages: a soft formula and a matte finish.', 4, 2, 'MAKEUP',
     '#8e4e4f', '1.7 g', 'assets/images/makeup/makeup12.jpg'),
    ('The City Mini Palette', 'Shadows do not dust and stay on the eyelids for a long time. Suitable for those who wear lenses. Can be applied both with a brush and with the fingers. Shimmer shades lay more beautifully and unfold when using the finger technique. You can choose between matte and shiny texture. They do not clump together in the folds of the eyelids when applied to the base.', 1, 7.5, 'MAKEUP',
     '#9d7c73', '6 g', 'assets/images/makeup/makeup13.jpg'),
    ('Sweet Cheeks Matte Blush', E'- a rich shade palette that allows you to mix colors;\n- highly pigmented formula;\n- silky texture that is pleasant to apply;\n- creates an excellent tinted coating' ||
        ' of the desired intensity;\n- provides a natural and stable finish;\n- ideal for both home and professional use.', 5, 7.5, 'MAKEUP', '#ac8a80',
     '5 g', 'assets/images/makeup/makeup14.jpg'),
    ('Control Freak Eyebrow Gel', 'Thanks to its unique composition, NYX Professional Makeup Control Freak Eyebrow Gel allows you to control even thick and unruly hairs. It can be applied on top of shadows and pencil, you will not harm your favorite shade, but only emphasize its saturation. The gel perfectly smooths the eyebrows, and also gives them the shape you originally intended. Active components of extreme resistance allow the product to control the movement of hairs throughout the day, regardless of strong wind, temperature changes and other weather conditions.', 5, 7, 'MAKEUP',
     '#ffffff', '9 g', 'assets/images/makeup/makeup15.jpg'),
    ('Volume Million Lashes Classic', 'Cosmetics give the mirror of the soul expressiveness and depth, make the look open and insightful. The brush moves smoothly, separating and lifting the eyelashes. Hairs are twisted, dyed neatly and evenly. The natural waxes in the composition preserve the touching curve throughout the day. Glycerin and jojoba oil nourish and strengthen eyelashes, solving problems of loss and thinning.', 2, 8.93, 'MAKEUP', '#000000', '10.7 ml', 'assets/images/makeup/makeup16.jpg'),
    ('Brilliant Signature Plump', 'The gloss is easy to apply, evenly distribute and draw an even contour. The consistency of the gloss differs depending on the shade, because the brand presented both regular cream shades and shimmer ones. Find your perfect shade and drive everyone crazy with flawless and seductive lip makeup!', 2, 7.39, 'MAKEUP', '#e8a7a5', '7 ml', 'assets/images/makeup/makeup17.jpg'),
    ('Micellar Water', 'Micellar water contains micelles — microparticles that attract various impurities like a magnet. Now you can clean your skin without friction and extra effort.', 2, 4.41, 'MAKEUP', '#ffffff', '400 ml', 'assets/images/makeup/makeup18.jpg'),
    ('Master Prime 50 Hydrating', 'Master Prime 50 Hydrating was specially developed for owners of dry, flaky skin. The tool perfectly hides small imperfections, evens out the skin relief, moisturizes, preparing for the application of foundation or powder. Thanks to its unique formula and weightless consistency, the cosmetic product is easy to apply and evenly distributed over the surface, at the same time not clogging pores and not weighing down makeup.', 1, 6.68, 'MAKEUP', '#ffffff', '30 ml', 'assets/images/makeup/makeup19.jpg'),
    ('Pure Color Envy Sculpting Lipstick', 'A wonderful shade will bring a holiday into your life and give pleasure. Color intensity is provided by True Vision technology, which gives lips volume and helps to adjust their shape. The color lasts up to six hours.', 6, 19.02, 'MAKEUP', '#9e434c', '3.5 g', 'assets/images/makeup/makeup20.jpg'),
    ('Estee', 'The "base" of the fragrance is built on a floral combination of Moroccan rose, carnation and jasmine. The final chord is like a gentleman kissing your hand. It touches your body with a combination of persistent musk, sandalwood and Yugoslavian moss.', 6, 70.41, 'PERFUMERY', '#e3e6d9', '50 ml', 'assets/images/perfumery/perfumery21.jpg'),
    ('Chance', 'Chanel Chance Eau de Parfum is an indicator of excellent taste, sophistication and femininity. Despite its huge popularity, this fragrance has not lost the true beauty of the composition and its uniqueness. Chanel Chance Eau de Parfum continues to gain fans at the same rate as before. This fragrance radiates energy, freshness and lightness. It is suitable for both adult women and young girls.', 7, 113.91, 'PERFUMERY', '#fee9cc', '35 ml', 'assets/images/perfumery/perfumery22.jpg'),
    ('Coco Mademoiselle Eau De Parfum Intense', 'The aroma "absorbed" oriental and woody chords, but you will hear the floral gamut in the composition in a less bright version. The opening notes of Calabrian bergamot, lemon and Sicilian orange create an extravaganza of freshness. In the chords of the "heart" plays a trio of jasmine, rose and fruit, forming a feminine composition. White musk, tonka bean, labdanum, patchouli and Madagascar vanilla fill the fragrance with richness, brightness and excellent persistence, which are characteristic of Chanel fragrances.', 7, 101, 'PERFUMERY', '#f5e2db', '35 ml', 'assets/images/perfumery/perfumery23.jpg'),
    ('Miss Dior Blooming Bouquet', 'The opening notes of the composition are the unbridled freshness of the river, represented by ripe orange and a combination of several other citrus fruits. The heart note is the elegance of majestic red rose and peony. An unforgettable aftertaste is created by persistent musk, complemented by the incredible aromas of patchouli. Blooming Bouquet is a fragrance of tenderness and femininity.', 9, 94.73, 'PERFUMERY', '#eee5e8', '100 ml', 'assets/images/perfumery/perfumery24.jpg'),
    ('Bright Crystal Absolu', 'Italian perfumers managed to combine in one bottle a stunning collection of truly stunning components, each of which certainly deserves attention. Peony, pomegranate, magnolia, lotus and yuzu, skilfully seasoned with musk, can emphasize a womans image and distinguish it from others.', 8, 31.31, 'PERFUMERY', '#fbb6ef', '30 ml', 'assets/images/perfumery/perfumery25.jpg'),
    ('Crystal Noir', 'A luxurious women''s fragrance is able to emphasize all the main virtues of a woman, as well as give the image a light mystery. With such a fragrance, you feel confident in any situation. With its complex composition, the smell of Crystal Noir is able to enchant and capture men''s hearts. Despite the fact that there are sweet oriental notes in the aroma, floral shades make it noble. Once you use Versace Crystal Noir Eau de Toilette, you will never want to part with it!', 8, 32.57, 'PERFUMERY', '#c3545d', '30 ml', 'assets/images/perfumery/perfumery26.jpg'),
    ('Dylan Blue Pour Homme', 'The composition opens with a wonderful combination of grapefruit, bergamot, sprinkled with aquatic notes and tart fig leaves. In the continuation, fiery black pepper, ambroxan molecules, the warmth of fragrant patchouli, the exquisite masterpiece of papyrus wood and the tenderness of violet come into force. And at the end, the composition pours out its luxurious plume, woven from musk, bitter tonka beans and majestic saffron.', 8, 84.47, 'PERFUMERY', '#0d2f55', '200 ml', 'assets/images/perfumery/perfumery27.png'),
    ('Pour Homme', 'Eau de toilette, which does not contain exotic elements, is intended for strong and courageous people who confidently walk through life.
The opening note of the fragrance opens with sensual neroli, tonic lemon peel and orange leaves with a bitter aftertaste. The "heart" note is revealed by a floral composition that includes hyacinth, geranium and nutmeg. The trailing note sounds like a woody accord, as well as a duet of ambergris and musk, which create the final image of the perfume.', 8, 41.63, 'PERFUMERY', '#bdd3ea', '100 ml', 'assets/images/perfumery/perfumery28.png'),
    ('Man Eau Fraiche', 'Eau Fraiche perfume, as if carved from coastal stones by a sea wave, endows its owner with natural charisma, charm and confidence in the future. Their extraordinary freshness is made possible by the combination of white lemon, carambola and rosewood.', 8, 6.29, 'PERFUMERY', '#dff8fd', '5 ml', 'assets/images/perfumery/perfumery29.png'),
    ('Jadore', 'A sweet and intoxicating drink in which the most exquisite and charming aromas have been successfully combined. A refreshing fruit cocktail reminiscent of the past summer. And a charming bouquet, skillfully composed of the most fragrant flowers. Here is the best feature of Jadore Eau de Parfum by Christian Dior. Its floral-fruity base is a genius creation that will exceed all your expectations.', 9, 58.05, 'PERFUMERY', '#e8e0dd', '30 ml', 'assets/images/perfumery/perfumery30.png'),
    ('Addict Eau Fraiche', 'Unique and noble perfumes, which cause boundless delight, are designed to give their owner - a young and optimistic girl - spring freshness throughout the year. The owner of Addict Eau Fraiche chooses endless games with emotions and frank feelings, she believes only in the most beautiful and expects something magical from the future. Light floral fragrances envelop freshness and energy, emphasize charm and elegance, and give a wonderful mood.', 9, 93.24, 'PERFUMERY', '#fff0f0', '100 ml', 'assets/images/perfumery/perfumery31.png'),
    ('Pure Poison', 'This exquisite and mysterious floral fragrance emphasizes the most attractive female features. Unforgettable charm is given by a light trail, which is left by a combination of fragrant orange blossom and white ambergris, which complete the perfume composition.', 9, 53.94, 'PERFUMERY', '#d2c9e6', '30 ml', 'assets/images/perfumery/perfumery32.png'),
    ('Allure', 'Chanel Allure fragrance is an exquisite and emotional burst of sensuality and allure. Created by Chanel in 1996, this fragrance impressed all women with its, unlike its predecessor, bouquet consisting of lemon and bourbon vanilla, vetiver, May rose and jasmine.', 7, 135.33, 'PERFUMERY', '#fef6e9', '50 ml', 'assets/images/perfumery/perfumery33.png'),
    ('Bleu de Chanel Eau de Parfum', 'The composition of the fragrance combines charming woody chords, supported by spicy oriental sounds and enticing citrus splashes.
The opening note attracts and envelops in a cloud of oriental sound, unfolding into mystical labdanum, sensual sandalwood and sweet patchouli leaves, spiced with ginger and nutmeg. Noble vetiver reigns in the "heart" of the composition, citrus aromas intertwine with woody streams, which are carefully distinguished by mint and jasmine.', 7, 105.52, 'PERFUMERY', '#1b262c', '50 ml', 'assets/images/perfumery/perfumery34.png'),
    ('N5', 'Chanel N5 is a timeless classic. This bouquet can be considered innovative, because it used aldehydes for the first time in order to slightly calm down the very rich aroma of flowers. This fragrance from Chanel is unique and unique. It attracts, shocks, mesmerizes, inspires... The unique bouquet of jasmine, roses and lilies of the valley was designed to become the most recognizable and respected perfume of all time.', 7, 117.55, 'PERFUMERY', '#fdb002', '35 ml', 'assets/images/perfumery/perfumery35.png');